---
title: "notater_fra_nils_og_emil"
format: html
---



Når man studerer strømpriser, er det viktig å være klar over flaskehalsene som oppstår. Strøm er feskvare, da det er utfordrene å lagre strømmen over lang tid (dette krever store batterifabrikker som er svært dyre). I henhold til elementær markedsteori, 


det at vi ikke har delt konsumenter og produsenter, gjør ingenting

kan fange opp etstimatne for godt

treatment i norge, som ikke gjelder alle. alle velger det ikke. 
  - elastsitenen for høyt og lavt forbruk

er det et problem med manglende random sample
  - matmoms i sverige mot strømstøtte i Norge
    - matmoms kom et år etter Norgespris
korrigere for generelle trender
  
  
det finnes studier for dette
  - undersøke dette
  
  
  
Når man studerer strømpriser, er det viktig å være klar over flaskehalsene som oppstår. Strøm er feskvare, da det er utfordrene å lagre strømmen over lang tid (dette krever store batterifabrikker som er svært dyre). I henhold til elementær markedsteori, 


- datasentere på sørlandet
  - krever arbeidsplasser
  For fabrikker som Morrow Batteries i Arendal og Elinor Batteries i Orkland (Midt-Norge) handlet plasseringen i stor grad om nærhet til markedet:
• Tunge transporter: Batterier er ekstremt tunge komponenter. Å frakte råmaterialer inn og ferdige battericeller ut fra Nord-Norge til de store bilprodusentene i Sentral-Europa gir høye transportkostnader og lang leveringstid.
• Klyngeeffekter: Sør-Norge har kortere vei til europeiske havner og tettere integrasjon med eksisterende prosessindustri og materialteknologi, som for eksempel Vianode på Herøya.
- melkeøya som tømmer nordnorge for kraft
- 
  
  
