---
title: "Plott for strompriser"
format: docx
warning: false
---
```{r}
#| echo: false
#| 
library(httr); library(jsonlite);  library(lubridate); library(zoo); library(rugarch); library(plm); library(vars) ; library(tidyverse)

```

## Henter du datasettene fra maskinen
```{r}

strompriser_norge_wide <- readRDS("C:/Users/ragnh/OneDrive/Dokumenter/Termpaper_ECON3170_2026/Datasett/strompris_norge_wide.rds")

strompriser_norge_long <- readRDS("C:/Users/ragnh/OneDrive/Dokumenter/Termpaper_ECON3170_2026/Datasett/strompris_norge_long.rds")
forventing_mot_forbruk <- readRDS("C:/Users/ragnh/OneDrive/Dokumenter/Termpaper_ECON3170_2026/Datasett/forventing_mot_forbruk_norge.rds")

```



```{r}
p1 <- strompriser_norge_long |>
  ggplot(aes(x = datetime, y = pris, color = prisomrade)) + geom_line()

p1

```


```{r}

p2 <- strom_norge |>
  dplyr::filter(prisomrade %in% c("NO4"))|>
  mutate(tid_pa_dagen = hour(datetime),ar = as.factor(year(datetime)))|>
 
  summarise(strompris = mean(pris, na.rm = TRUE), .by = c(tid_pa_dagen,ar))|>
  arrange(tid_pa_dagen) |>
  ggplot(aes(x = tid_pa_dagen, y = strompris, color = ar)) +
  geom_line()


p2

```


Nå har flere kommet tilbake på kontoret, slik at strømprisen midt på dagen går ned. Når vi var hjemme hele dagen, var det et relativt konstant forbruk av  strøm gjennom hele vår våkne tilstand.

#Kombinerer de to datasettene for forvenet strømforbruk, og strømpris

```{r}

strompriser_mot_forventing <- forventing_mot_forbruk |>
  left_join(strompriser_norge_long, by = c("datetime", "prisomrade")) 

nrow(strompriser_mot_forventing)

strompriser_mot_forventing |>
  drop_na()

nrow(strompriser_mot_forventing)

```
