---
title: "Henting_av_data"
format: html
---

Det første vi gjør, er at vi imporerer alle pakkene vi strenger for prosjektet vårt. Disse kjører vi en gang, slik at de er importert når vi fortsetter å jobbe.
```{r}
#| echo: false
#| 
library(httr); library(jsonlite); library(dplyr); library(tidyr); library(lubridate); library(zoo); library(rugarch); library(plm); library(readr); library(vars) 

```

## Innsamling av data

Vi skal bruke API-er til å innhente dataen vi skal bruke for prosjektet. For å finne den historiske fyllingsgraden i vannmagasinene bruker vi datasett fra NVE




```{r}

hent_vannreservoar <- function(start_year = 1950,
                           end_year = 2024,
                           areas = c("NO1", "NO2", "NO3", "NO4", "NO5")) { #har initialverdier for funksjonen, som kan endres om ønskelig
  
  # URL til NVE sitt API
  url <- paste0(
    "https://biapi.nve.no/magasinstatistikk/",
    "api/Magasinstatistikk/HentOffentligData"
  )
  
  # Hent data
  data <- jsonlite::fromJSON(url)
  
  # Gjør om til dataframe og bearbeider det som en tibble
  reservoarer <- data |>
    dplyr::filter(
      iso_aar >= start_year,
      iso_aar <= end_year
    ) |>
    dplyr::mutate(
      prisomrade = paste0("NO", omrnr),
    ) |>
    dplyr::filter(
      prisomrade %in% areas
    ) |>
    dplyr::select(
      dato = dato_Id,
      prisomrade,
      fyllingsgrad,
      fyllingsgrad_forrige_uke
    ) |>
    dplyr::arrange(
      dato,
      prisomrade
    )
  
  return(reservoarer)
}

hent_vannreservoar()

```




```